_core:
  default_config_hash: XEpuHrBp3DELKxVx0tmwE6CS7NSIKXu4F6QhT_vwqd0
maxlength_block_class_field: 255
field_type: multiple_textfields
default_case: standard
block_classes_stored:
  - osu-bg-page-alt-1
  - border
  - container
  - px-3
  - py-2
enable_attributes: true
enable_auto_complete: true
qty_classes_per_block: 10
items_per_page: 50
enable_special_chars: false
qty_attributes_per_block: 10
enable_id_replacement: true
weight_attributes: 0
weight_class: 0
weight_id: 0
filter_html_clean_css_identifier: ''
maxlength_attributes: 255
maxlength_id: 255
attribute_keys_stored: '[]'
attribute_value_stored: '[]'
attributes_inline: '[]'
