_core:
  default_config_hash: yTxtFqBHnEWxQswuWvkjE8mKw2t8oKuCL1q8KnfHuGE
langcode: en
uuid: 648e63e1-8d4b-4748-b393-4f39ff04139f
name: 'Applied Magnetics Laboratory'
mail: noreply@mail.drupal.oregonstate.edu
slogan: ''
page:
  403: ''
  404: ''
  front: /node/1286
admin_compact_mode: false
weight_select_max: 100
default_langcode: en
