version: 1.3.0
services:
  - php:
      version: 7.4
events:
  build:
    steps:
      - composer:
          type: script
          script:
            - composer validate --no-check-all --ansi
            - composer install --no-progress --optimize-autoloader --no-dev
