version: 1.1.0
services:
  - php:
      version: 7.3
events:
  build:
    steps:
      - composer:
          type: script
          script:
            - composer validate --no-check-all --ansi
            - composer install --no-progress --optimize-autoloader
