version: 1.3.0
services:
  - php:
      version: 8.2
events:
  build:
    steps:
      - composer:
          type: script
          script:
            - composer validate --no-check-all --ansi
            - composer install --no-progress --optimize-autoloader --no-dev

variables:
  global:
    COMPOSER_AUTH:
      secure: 2acTCpsMeWpSXvGP/VbYAJEf6mCUhpcHhMCIHluIzUEH5mpNppgJcGq6TSyytyB5MLhjBNCeDKNI+PeTAzRkyatxQpQWxlMvUzgxdaPV36CvWNimH1DDUNU1DGZE3TwXC5BgJXkIR1Ib/xC9HzD8IWdBwr3dxcM5aOlLbLzcWdwIVbNab9EAR4KOYgYu50uyC6IF2WXguy1gt/2INO14mAC5nHKq92hdVFvXaGTousQxBn0/VxdtOL11sARQi+heub92w6Yx/8ePGwj1kc0VeBFdPnJKK9VJniEYbYeOAOmN6IF7VKzl3s5e/ySwCh5Z/qIeVEOlPeSsSuoyx2KETXId27GaXXPx9zxJqB+XRehsCrpp0QToR85lZEc8/h6/K/ENNc+QRPIp91wZX1jvau2nYvfELPyswdW0Rzn6QMHL5pZ90k4I9w4HU64TX4lBGPbVWNatgWQ7qcnNjwpVOtY9bnrbOl6UffAPJYXbBlnM2w6i+KTzAbCvgJSW7ZnXwfy//dcPibt2ekTTn97xRQkEh+7e06oZnymvLaXyZ/PYqYdU2kABiickI8S7V0ZbUqpImTI0nE8y2cvVRTYqLQfCYw8thCqxksHnCuJZ/Mr7C78SdZ7IRFfSKEsMFoMMC25HzN92EYXLmT4DfWYKmqjXXTr1+RdhJD77PPfooVIcjY=7k6cJUBx4DoPGIPjuI/DntCVzQ/AW/eOeER/sQc8DaJ2sxwGoj83l9X93aX4zKFQItsVRW7nuUyjXLOggvp9z6cN7b+a0hTRuUZwcRC2vdkpHTqLEG9J+5ILdUpCh2cr4/JmVyfylwiBHDndsHlsLDgxlxmnG2oXL0qx5SGjmNoqIj9DzrlOko5hyDrv5wb7w6Lh6sQdf8vU02zcRzpGdWyXoClvM+AxqSXz4jiQ/BY=
