version: 1.3.0
services:
  - php:
      version: 8.3
events:
  build:
    steps:
      - composer:
          type: script
          script:
            - composer validate --no-check-all --ansi
            - composer install --no-progress --optimize-autoloader --no-dev

variables:
  global:
    COMPOSER_AUTH:
      secure: 2acRvA1xHfNLjDX/2REJb2u4gABr3T5zQGjxdL0xtxjSPW/bNX3ezM+saX2KM8Q0+njigCpdcXuOjvoZ/pccy9JAtAiWcdQZNFxmSyH6H/IVY20CQnuuML6IH2EJxQBZ0oOVWCsn9g919lKQfwIoTijfwPk1fsSzIIKCwaDiC7U7H7n6Bs4WhU9CMX9S+T+HTxhZTdRbuvkGUhOpBUyANFAbgX6HZTipTP6D0psJtgW+52rZNHxLYyPsE0c6dI0lQXSJlspgmqyQ5ADt6IEqUccH6Hgp+EOpMIDcsL2gd/V1/bRD1odZoRitoGZ9683Dk7XadI/q6w0ecoIlMC0geoXBHVyL80pPD9DuX7W74ffK/NxOUbL7uTyy2Wp7ojdsBktAMTRzALFfZn4eqenC2+iyWIxudliItFtp/CtHt/lHlicROkXVMzQydPufUiXTwFdg9eJwjFdaRieyT1pzerITvML4fJkwt6XHjoSUyXadYIXwIBnoQX9TAI7xn8Wc8Lwjn3A1DIdW3/9wEmQaqSYUvqw7W93AIHUlkAuurBs30jSZ96XlSMl3T2DDonmdrbkQd5lcyk6DfjMOYr8ukZLRuYJbZokl82uEbXHrn8X7osc3f93pQkdrniE/oBy06dmoS0DXEa0bq0I93Wgy5PF6SL4Sm71YT5o47Qnzg2agq4=/j360TxGrnZa016/62Kf5AP6UkiYXRZ5a0FYb+wqBkj2ODtjiGU+/wBblWsqW/RsXn0F3Ajp+O8BFNh9/sW11FQMxXV4XdaJk9oWcTUsv+bI+t8fC1UC6ggpR5eEmdtqyWswW27yJl/rhPjzCqzYyKa18PuzmFUlw4fCpTb292lS+kZCDU2U5V2chdH3lrZYjgXiiu9ahv3DDhwT2jVHkg==
