_core:
  default_config_hash: 8ZvIySyDhPsULv0PXRAyHj9qvAcp1qfTMNRHGCxj5rU
content_root: ''
assertiveness: smart
no_load: ''
ignore_all_if_absent: ''
ignore_elements: '.filter-guidelines-item *,#toolbar-administration *,nav *,.block-local-tasks-block *,.block-group-operations *'
embedded_content_warning: ''
download_links: ''
link_strings_new_windows: ''
ignore_link_strings: ''
link_ignore_selector: 'svg.ext, svg.mailto, .link-purpose-text'
hidden_handlers: ''
ed11y_theme: sleekTheme
shadow_components: ''
disable_sync: false
preserve_params: 'search,keys,page,language,language_content_entity'
redundant_prefix: ''
custom_tests: 1
disable_live: false
live_h2: 'form[id^="node-"] #edit-body-wrapper .ck-content'
ck5_table_headers: row
