_core:
  default_config_hash: yTxtFqBHnEWxQswuWvkjE8mKw2t8oKuCL1q8KnfHuGE
langcode: en
uuid: 972e020f-4049-4239-b9cd-76346ba703cf
name: 'Beaver Nation'
mail: noreply@mail.drupal.oregonstate.edu
slogan: ''
page:
  403: ''
  404: ''
  front: /node/11
admin_compact_mode: false
weight_select_max: 100
default_langcode: en
