_core:
  default_config_hash: yTxtFqBHnEWxQswuWvkjE8mKw2t8oKuCL1q8KnfHuGE
langcode: en
uuid: fbb65df5-a648-4e13-a7be-e2c11f7ddd8e
name: 'OSU Retirement Association'
mail: noreply@mail.drupal.oregonstate.edu
slogan: ''
page:
  403: ''
  404: ''
  front: /node/3
admin_compact_mode: false
weight_select_max: 100
default_langcode: en
mail_notification: null
