name: 'OSU Tours'
description: 'Provides Tours for OSU Drupal'
type: 'User Interface'
install:
  - tour
  - osu_tours
config:
  actions:
    user.role.authenticated:
      grantPermission: 'access tour'
    user.role.dx_administrator:
      grantPermission: 'administer tour'
    tour.settings:
      simpleConfigUpdate:
        hide_tour_when_empty: true
        display_custom_labels: true
        tour_avail_text: 'Take a tour of this page.'
        tour_no_avail_text: 'No tour available for this page.'
