_core:
  default_config_hash: 3I9c-HSRx44YhsbKiZfrXkx6Kk7cxYO9WLg__NOyOuo
langcode: en
default_challenge: recaptcha/reCAPTCHA
description: 'This question is for testing whether or not you are a human visitor and to prevent automated spam submissions.'
administration_mode: false
whitelist_ips: ''
wrong_captcha_response_message: 'The answer you entered for the CAPTCHA was not correct.'
default_validation: 1
persistence: 1
enable_stats: false
log_wrong_responses: false
enabled_default: 0
allow_on_admin_pages: false
add_captcha_description: true
