_core:
  default_config_hash: 1em5JafD7VbiJO44inPINOhOpDOLJPgSK5HSHEcA8_Y
nid_list:
  - 2
  - 11
  - 6
translation_sync: true
search: true
type: hidden
content_types:
  page: user
  osu_profile: all
  osu_simple_tabs: all
content_type_modes:
  page:
    - full
  osu_profile:
    - full
  osu_simple_tabs:
    - simple_tab_content
