_core:
  default_config_hash: 2KFJzvzcRM1w9DA9Ot84ihjq4ofMKAv4TpEs6gc1xCg
show_on_admin: false
alert_styles: "osu-info|Information Blue\r\nosu-success|Success Green\r\nosu-warning|Warning Yellow\r\nosu-danger|Very Important Red"
display_order: ascending
automatic_refresh: true
refresh_interval: 15
cache_max_age: 15
