_core:
  default_config_hash: yTxtFqBHnEWxQswuWvkjE8mKw2t8oKuCL1q8KnfHuGE
langcode: en
uuid: f76c281e-c599-464d-8d99-a7ad116a033c
name: 'Educational Opportunities Program'
mail: noreply@mail.drupal.oregonstate.edu
slogan: ''
page:
  403: ''
  404: ''
  front: /node/3
admin_compact_mode: false
weight_select_max: 100
default_langcode: en
