_core:
  default_config_hash: WqZtf-1qkwxkhMQQxgxAOTGvuc0cQwb3zXtbXZX4GeQ
content_root: ''
assertiveness: smart
no_load: ''
ignore_all_if_absent: ''
ignore_elements: '.block-local-tasks-block *,.block-group-operations *'
embedded_content_warning: ''
download_links: ''
ignore_link_strings: ''
hidden_handlers: ''
ed11y_theme: sleekTheme
shadow_components: ''
disable_sync: false
preserve_params: 'search,keys,page,language,language_content_entity'
custom_tests: 1
disable_live: false
live_h2: 'form[id^="node-"] #edit-body-wrapper .ck-content'
ck5_table_headers: row
