_core:
  default_config_hash: 4GIX5Esnc_umpXUBj4IIocRX7Mt5fPhm4AgXfE3E56E
module:
  auto_entitylabel: -100
  acquia_connector: 0
  acquia_purge: 0
  address: 0
  admin_toolbar: 0
  admin_toolbar_search: 0
  admin_toolbar_tools: 0
  asset_injector: 0
  better_exposed_filters: 0
  big_pipe: 0
  block: 0
  block_class: 0
  block_content: 0
  block_visibility_groups: 0
  block_visibility_groups_admin: 0
  bootstrap_layout_builder: 0
  bootstrap_styles: 0
  breakpoint: 0
  captcha: 0
  cas: 0
  cas_attributes: 0
  charts: 0
  charts_blocks: 0
  charts_highcharts: 0
  charts_highcharts_drilldown: 0
  ckeditor: 0
  ckeditor_div_manager: 0
  ckeditor_liststyle: 0
  ckeditor_scayt: 0
  colorbox: 0
  config: 0
  contextual: 0
  crop: 0
  ctools: 0
  ctools_block: 0
  ctools_views: 0
  date_ap_style: 0
  datetime: 0
  datetime_range: 0
  default_content: 0
  dropzonejs: 0
  dynamic_page_cache: 0
  easy_breadcrumb: 0
  editor: 0
  editor_advanced_link: 0
  editor_file: 0
  editoria11y: 0
  entity: 0
  entity_reference_revisions: 0
  entitygroupfield: 0
  exclude_node_title: 0
  feeds: 0
  feeds_ex: 0
  feeds_tamper: 0
  field: 0
  field_group: 0
  field_ui: 0
  file: 0
  file_mdm: 0
  file_mdm_exif: 0
  file_mdm_font: 0
  filter: 0
  filter_perms: 0
  flexible_permissions: 0
  focal_point: 0
  fontawesome: 0
  gnode: 0
  google_analytics: 0
  google_cse: 0
  google_tag: 0
  group: 0
  group_content_menu: 0
  group_support_revisions: 0
  help: 0
  history: 0
  honeypot: 0
  image: 0
  image_effects: 0
  imagemagick: 0
  jquery_ui: 0
  jquery_ui_autocomplete: 0
  jquery_ui_menu: 0
  layout_builder: 0
  layout_builder_blocks: 0
  layout_builder_component_attributes: 0
  layout_builder_operation_link: 0
  layout_builder_restrictions: 0
  layout_builder_restrictions_by_region: 0
  layout_discovery: 0
  libraries: 0
  link: 0
  linkit: 0
  linkpurpose: 0
  media: 0
  media_bulk_upload: 0
  media_bulk_upload_dropzonejs: 0
  media_entity_file_replace: 0
  media_library: 0
  media_library_form_element: 0
  memcache: 0
  menu_link_content: 0
  menu_ui: 0
  metatag: 0
  metatag_google_cse: 0
  metatag_open_graph: 0
  metatag_twitter_cards: 0
  metatag_verification: 0
  metatag_views: 0
  migrate: 0
  migrate_drupal: 0
  migrate_plus: 0
  module_filter: 0
  mysql: 0
  node: 0
  node_revision_delete: 0
  oembed_providers: 0
  og_to_group: 0
  options: 0
  osu_block_types: 0
  osu_bootstrap_layout_builder: 0
  osu_ckeditor_plugins: 0
  osu_default_content: 0
  osu_google_tag: 0
  osu_groups: 0
  osu_groups_basic_group: 0
  osu_icon_field: 0
  osu_library_hero: 0
  osu_library_three_column_cards: 0
  osu_library_three_column_equal: 0
  osu_library_two_column_25_75: 0
  osu_library_two_column_50_50: 0
  osu_media: 0
  osu_migrate_content: 0
  osu_migrations: 0
  osu_migrations_files: 0
  osu_migrations_media: 0
  osu_migrations_taxonomy: 0
  osu_profile: 0
  osu_roles: 0
  osu_seckit: 0
  osu_simple_popup_blocks: 0
  osu_simple_tabs: 0
  osu_sitewide_alert: 0
  osu_story: 0
  osu_user_accounts: 0
  osu_user_to_profiles: 0
  page_cache: 0
  paragraphs_to_layout_builder: 0
  path: 0
  path_alias: 0
  phpass: 0
  purge: 0
  purge_drush: 0
  purge_file: 0
  purge_processor_cron: 0
  purge_processor_lateruntime: 0
  purge_queuer_coretags: 0
  purge_tokens: 0
  purge_ui: 0
  recaptcha: 0
  redirect: 0
  responsive_preview: 0
  responsive_table_filter: 0
  search: 0
  seckit: 0
  section_library: 0
  serialization: 0
  shortcut: 0
  simple_popup_blocks: 0
  sitewide_alert: 0
  smart_date: 0
  sophron: 0
  superfish: 0
  syslog: 0
  system: 0
  tamper: 0
  taxonomy: 0
  telephone: 0
  text: 0
  text_field_formatter: 0
  toc_js: 0
  toc_js_per_node: 0
  token: 0
  toolbar: 0
  tour: 0
  update: 0
  user: 0
  views_bootstrap: 0
  views_bulk_edit: 0
  views_bulk_operations: 0
  views_conditional: 0
  views_taxonomy_term_name_depth: 0
  views_ui: 0
  webform: 0
  webform_access: 0
  webform_attachment: 0
  webform_node: 0
  webform_ui: 0
  xmlsitemap_custom: 0
  pathauto: 1
  webform_bootstrap: 1
  xmlsitemap: 1
  externalauth: 10
  views: 10
  paragraphs: 11
  osu_standard: 1000
theme:
  claro: 0
  stable9: 0
  madrone: 0
profile: osu_standard
