_core:
  default_config_hash: yTxtFqBHnEWxQswuWvkjE8mKw2t8oKuCL1q8KnfHuGE
langcode: en
uuid: 936836fc-8c64-47d0-9c61-450fddafaf19
name: 'National Geoelectromagnetic Facility'
mail: noreply@mail.drupal.oregonstate.edu
slogan: ''
page:
  403: ''
  404: ''
  front: /node/3
admin_compact_mode: false
weight_select_max: 100
default_langcode: en
