_core:
  default_config_hash: yTxtFqBHnEWxQswuWvkjE8mKw2t8oKuCL1q8KnfHuGE
langcode: en
uuid: 3fec34c1-cbae-4f8f-a8c5-41fcaa5c8380
name: 'Oregon State Advance'
mail: noreply@mail.drupal.oregonstate.edu
slogan: ''
page:
  403: ''
  404: ''
  front: /node/2
admin_compact_mode: false
weight_select_max: 100
default_langcode: en
