_core:
  default_config_hash: IKv_fwTBXX39qcAA-2Gbncs4a5SBNY-6wknThHHrNQQ
content_root: ''
no_load: ''
ignore_all_if_absent: ''
ignore_elements: '.filter-guidelines-item *,#toolbar-administration *,nav *,.block-local-tasks-block *,.block-group-operations *'
embedded_content_warning: ''
assertiveness: smart
download_links: ''
ignore_link_strings: ''
link_strings_new_windows: ''
link_ignore_selector: 'svg.ext, svg.mailto, .link-purpose-text'
hidden_handlers: ''
ed11y_theme: sleekTheme
shadow_components: ''
disable_sync: false
preserve_params: 'search,keys,page,language,language_content_entity'
redundant_prefix: ''
custom_tests: 1
ck5_table_headers: row
