_core:
  default_config_hash: yTxtFqBHnEWxQswuWvkjE8mKw2t8oKuCL1q8KnfHuGE
langcode: en
uuid: af0420de-aac5-4c87-9c21-4d006744ed0c
name: 'Office of Youth Safety & Compliance'
mail: noreply@mail.drupal.oregonstate.edu
slogan: ''
page:
  403: ''
  404: ''
  front: /node/31
admin_compact_mode: false
weight_select_max: 100
default_langcode: en
