_core:
  default_config_hash: JPyi0Uf1PYAjt6pr0FIwOo6EQ6wpxjteQdVpVOTyvR4
languages:
  - 'da_DK|Danish (Denmark)'
  - 'de_DE|German (Germany)'
  - 'el_GR|Greek (Greece)'
  - 'en_CA|Canadian English'
  - 'en_GB|British English'
  - 'en_US|American English'
  - 'es_ES|European Spanish'
  - 'fi_FI|Finnish (Finland)'
  - 'fr_CA|Canadian French'
  - 'fr_FR|French (France)'
  - 'it_IT|Italian (Italy)'
  - 'nb_NO|Norwegian Bokmål (Norway)'
  - 'nl_NL|Dutch (Netherlands)'
  - 'sv_SE|Swedish (Sweden)'
