_core:
  default_config_hash: fMTQlRT4MXb9WtflmxsvPI0VnKTQNjOnlx9oCWO3vYo
buttons_size: 32
additional_html: "<a class=\"a2a_button_facebook\"></a>\r\n<a class=\"a2a_button_x\"></a>\r\n<a class=\"a2a_button_mastodon\"></a>\r\n<a class=\"a2a_button_linkedin\"></a>\r\n<a class=\"a2a_button_email\"></a>"
additional_css: ''
additional_js: ''
universal_button: default
custom_universal_button: ''
universal_button_placement: before
entities:
  media: 1
  node: 1
  comment: 1
  block_content: 0
  contact_message: 0
  feeds_feed: 0
  feeds_subscription: 0
  file: 0
  group_config_wrapper: 0
  group: 0
  group_content: 0
  group_content_menu: 0
  menu_link_content: 0
  path_alias: 0
  redirect: 0
  section_library_template: 0
  shortcut: 0
  taxonomy_term: 0
  user: 0
  webform_submission: 0
  paragraph: 0
