_core:
  default_config_hash: Ytm7bJfO_TyebetmSWGF2NscXlvoPOXpBmCuMMUpiGc
minimum_lifetime: 86400
xsl: 1
prefetch_aliases: 1
chunk_size: auto
batch_limit: 100
path: xmlsitemap
frontpage_priority: 1.0
frontpage_changefreq: 86400
lastmod_format: 'Y-m-d\TH:i\Z'
gz: false
clean_url: 0
disable_cron_regeneration: false
i18n_selection_mode: simple
metatag_exclude_noindex: false
cron_threshold_error: 1209600
cron_threshold_warning: 172800
