_core:
  default_config_hash: yTxtFqBHnEWxQswuWvkjE8mKw2t8oKuCL1q8KnfHuGE
langcode: en
uuid: ee95360f-fe21-41b9-bcd2-5e4daa0d7edd
name: 'Division of Research and Innovation'
mail: noreply@mail.drupal.oregonstate.edu
slogan: ''
page:
  403: ''
  404: ''
  front: /node/2956
admin_compact_mode: false
weight_select_max: 100
default_langcode: en
mail_notification: null
