channels:
  0:
    id: purgers
    grants:
      - 0
      - 2
      - 3
  1:
    id: queue
    grants:
      - 0
      - 2
      - 3
  3:
    id: diagnostics
    grants:
      - 3
  4:
    id: purger_acquia_purge_c5fa2473b3
    grants:
      - 0
      - 2
      - 3
