identifier: madrone_announcementfortrainings
uid: training_announcement
type: '0'
css_selector: '1'
layout: '2'
visit_counts: 'a:1:{i:0;s:1:"0";}'
overlay: 0
trigger_method: '0'
trigger_selector: '#custom-css-id'
enable_escape: 1
delay: 0
minimize: 0
close: 1
use_time_frequency: 0
time_frequency: '3600'
show_minimized_button: 0
width: '400'
cookie_expiry: '100'
status: null
