_core:
  default_config_hash: yTxtFqBHnEWxQswuWvkjE8mKw2t8oKuCL1q8KnfHuGE
langcode: en
uuid: 2943134d-783e-40eb-bf28-a327c3d8338b
name: OSU-Cascades
mail: noreply@mail.drupal.oregonstate.edu
slogan: ''
page:
  403: ''
  404: ''
  front: /node/2
admin_compact_mode: false
weight_select_max: 100
default_langcode: en
mail_notification: null
