_core:
  default_config_hash: yTxtFqBHnEWxQswuWvkjE8mKw2t8oKuCL1q8KnfHuGE
langcode: en
uuid: 01e081d1-9b59-473a-a8bf-3e70f3b46112
name: TRiO
mail: noreply@mail.drupal.oregonstate.edu
slogan: ''
page:
  403: ''
  404: ''
  front: /node/101
admin_compact_mode: false
weight_select_max: 100
default_langcode: en
mail_notification: null
