_core:
  default_config_hash: 1em5JafD7VbiJO44inPINOhOpDOLJPgSK5HSHEcA8_Y
nid_list:
  - 2
  - 1
  - 6
translation_sync: true
search: true
type: hidden
content_types:
  page: user
  osu_profile: all
content_type_modes:
  page:
    - full
  osu_profile:
    - full
