_core:
  default_config_hash: yTxtFqBHnEWxQswuWvkjE8mKw2t8oKuCL1q8KnfHuGE
langcode: en
uuid: b6ca277d-2b57-424c-8496-4c0fbc66f331
name: 'Social Media'
mail: noreply@mail.drupal.oregonstate.edu
slogan: ''
page:
  403: ''
  404: ''
  front: /node/11
admin_compact_mode: false
weight_select_max: 100
default_langcode: en
