_core:
  default_config_hash: x6jSwNR53UxMX4r7I8QrQiFEJiCcMseWq92ttvEwBGk
nid_list:
  - 2
  - 1
  - 481
  - 486
  - 491
  - 496
  - 551
translation_sync: true
search: true
type: hidden
content_types:
  page: user
  osu_profile: all
content_type_modes:
  page:
    - full
  osu_profile:
    - full
