_core:
  default_config_hash: yTxtFqBHnEWxQswuWvkjE8mKw2t8oKuCL1q8KnfHuGE
langcode: en
uuid: aa7c451d-3fc7-4f77-b099-e6961607a931
name: 'Center for Teaching and Learning'
mail: noreply@mail.drupal.oregonstate.edu
slogan: ''
page:
  403: ''
  404: ''
  front: /node/551
admin_compact_mode: false
weight_select_max: 100
default_langcode: en
mail_notification: null
