_core:
  default_config_hash: OhBYZyMBbLkxkI5dWYWQANJcihno1rg3ZZls5yEfKCw
allowed_block_attributes:
  id: false
  class: true
  style: false
  data: true
allowed_block_title_attributes:
  id: false
  class: true
  style: false
  data: true
allowed_block_content_attributes:
  id: false
  class: true
  style: false
  data: true
