_core:
  default_config_hash: yTxtFqBHnEWxQswuWvkjE8mKw2t8oKuCL1q8KnfHuGE
langcode: en
uuid: 344e24ae-d17e-4be5-93e6-4e987f55cdd4
name: FacultySuccess@OregonState
mail: noreply@mail.drupal.oregonstate.edu
slogan: ''
page:
  403: ''
  404: ''
  front: /node/126
admin_compact_mode: false
weight_select_max: 100
default_langcode: en
