_core:
  default_config_hash: yTxtFqBHnEWxQswuWvkjE8mKw2t8oKuCL1q8KnfHuGE
langcode: en
uuid: d55e9c39-9f3e-4387-81ce-11ce4b6292b6
name: Commencement
mail: noreply@mail.drupal.oregonstate.edu
slogan: ''
page:
  403: ''
  404: ''
  front: /node/82481
admin_compact_mode: false
weight_select_max: 100
default_langcode: en
mail_notification: null
