_core:
  default_config_hash: Cbo8RBRfFI5Vp47ph18ipaTD93yRguohd7Tatbb_U1k
defaults:
  amount:
    status: true
    settings:
      amount: 25
  created:
    status: true
    settings:
      age: 2
  drafts:
    status: false
    settings:
      age: 1
disable_automatic_queueing: false
